import type { LocationCostOfLiving } from './types';

export const mockCostOfLivingData: Omit<LocationCostOfLiving, 'id' | 'lastUpdated'>[] = [
  {
    locationName: 'Tokyo',
    locationType: 'city',
    countryName: 'Japan',
    currencyCode: 'JPY',
    averageMealCost: 10,
    monthlyRent1BR: 1200,
    monthlyRent2BR: 1800,
    monthlyRent3BR: 2500,
    transportPassCost: 80,
    utilitiesMonthly: 200,
    internetMonthly: 40,
    childcareMonthly: 500,
    localPurchasingPowerIndex: 87.1,
    groceriesIndex: 85.0,
    restaurantPriceIndex: 48.5,
  },
  {
    locationName: 'Dubai',
    locationType: 'city',
    countryName: 'UAE',
    currencyCode: 'AED',
    averageMealCost: 15,
    monthlyRent1BR: 1800,
    monthlyRent2BR: 2500,
    monthlyRent3BR: 3500,
    transportPassCost: 70,
    utilitiesMonthly: 250,
    internetMonthly: 100,
    childcareMonthly: 800,
    localPurchasingPowerIndex: 91.5,
    groceriesIndex: 45.2,
    restaurantPriceIndex: 55.7,
  },
  {
    locationName: 'Zurich',
    locationType: 'city',
    countryName: 'Switzerland',
    currencyCode: 'CHF',
    averageMealCost: 30,
    monthlyRent1BR: 2500,
    monthlyRent2BR: 3500,
    monthlyRent3BR: 4800,
    transportPassCost: 90,
    utilitiesMonthly: 220,
    internetMonthly: 60,
    childcareMonthly: 2500,
    localPurchasingPowerIndex: 119.5,
    groceriesIndex: 129.8,
    restaurantPriceIndex: 123.8,
  },
  {
    locationName: 'Singapore',
    locationType: 'city',
    countryName: 'Singapore',
    currencyCode: 'SGD',
    averageMealCost: 12,
    monthlyRent1BR: 2800,
    monthlyRent2BR: 4000,
    monthlyRent3BR: 5500,
    transportPassCost: 100,
    utilitiesMonthly: 150,
    internetMonthly: 35,
    childcareMonthly: 1000,
    localPurchasingPowerIndex: 88.5,
    groceriesIndex: 82.1,
    restaurantPriceIndex: 61.3,
  },
  {
    locationName: 'Seoul',
    locationType: 'city',
    countryName: 'South Korea',
    currencyCode: 'KRW',
    averageMealCost: 9,
    monthlyRent1BR: 850,
    monthlyRent2BR: 1300,
    monthlyRent3BR: 2000,
    transportPassCost: 50,
    utilitiesMonthly: 180,
    internetMonthly: 25,
    childcareMonthly: 400,
    localPurchasingPowerIndex: 74.3,
    groceriesIndex: 96.6,
    restaurantPriceIndex: 43.1,
  },
  {
    locationName: 'London',
    locationType: 'city',
    countryName: 'United Kingdom',
    currencyCode: 'GBP',
    averageMealCost: 25,
    monthlyRent1BR: 2200,
    monthlyRent2BR: 3000,
    monthlyRent3BR: 4200,
    transportPassCost: 180,
    utilitiesMonthly: 250,
    internetMonthly: 35,
    childcareMonthly: 1500,
    localPurchasingPowerIndex: 91.2,
    groceriesIndex: 50.8,
    restaurantPriceIndex: 79.8,
  },
  {
    locationName: 'Amsterdam',
    locationType: 'city',
    countryName: 'Netherlands',
    currencyCode: 'EUR',
    averageMealCost: 20,
    monthlyRent1BR: 1800,
    monthlyRent2BR: 2500,
    monthlyRent3BR: 3200,
    transportPassCost: 100,
    utilitiesMonthly: 230,
    internetMonthly: 45,
    childcareMonthly: 1800,
    localPurchasingPowerIndex: 89.9,
    groceriesIndex: 65.4,
    restaurantPriceIndex: 84.1,
  },
];
