
import type { LocationCostOfLiving } from './types';

export const mockCostOfLivingData: Omit<LocationCostOfLiving, 'id' | 'lastUpdated'>[] = [
  {
    locationName: 'Tokyo',
    locationType: 'city',
    countryName: 'Japan',
    currencyCode: 'JPY',
    averageMealCost: 1500,
    monthlyRent1BR: 160000,
    monthlyRent2BR: 250000,
    monthlyRent3BR: 400000,
    transportPassCost: 15000,
    utilitiesMonthly: 20000,
    internetMonthly: 5000,
    childcareMonthly: 80000,
    localPurchasingPowerIndex: 87.1,
    groceriesIndex: 85.0,
    restaurantPriceIndex: 48.5,
  },
  {
    locationName: 'Dubai',
    locationType: 'city',
    countryName: 'UAE',
    currencyCode: 'AED',
    averageMealCost: 60,
    monthlyRent1BR: 7500,
    monthlyRent2BR: 11000,
    monthlyRent3BR: 15000,
    transportPassCost: 350,
    utilitiesMonthly: 850,
    internetMonthly: 350,
    childcareMonthly: 3000,
    localPurchasingPowerIndex: 91.5,
    groceriesIndex: 45.2,
    restaurantPriceIndex: 55.7,
  },
  {
    locationName: 'Zurich',
    locationType: 'city',
    countryName: 'Switzerland',
    currencyCode: 'CHF',
    averageMealCost: 30,
    monthlyRent1BR: 2300,
    monthlyRent2BR: 3200,
    monthlyRent3BR: 4500,
    transportPassCost: 90,
    utilitiesMonthly: 220,
    internetMonthly: 60,
    childcareMonthly: 2500,
    localPurchasingPowerIndex: 119.5,
    groceriesIndex: 129.8,
    restaurantPriceIndex: 123.8,
  },
  {
    locationName: 'Singapore',
    locationType: 'city',
    countryName: 'Singapore',
    currencyCode: 'SGD',
    averageMealCost: 15,
    monthlyRent1BR: 3800,
    monthlyRent2BR: 5200,
    monthlyRent3BR: 7000,
    transportPassCost: 150,
    utilitiesMonthly: 250,
    internetMonthly: 50,
    childcareMonthly: 1500,
    localPurchasingPowerIndex: 88.5,
    groceriesIndex: 82.1,
    restaurantPriceIndex: 61.3,
  },
  {
    locationName: 'Seoul',
    locationType: 'city',
    countryName: 'South Korea',
    currencyCode: 'KRW',
    averageMealCost: 12000,
    monthlyRent1BR: 1400000,
    monthlyRent2BR: 2200000,
    monthlyRent3BR: 3500000,
    transportPassCost: 70000,
    utilitiesMonthly: 250000,
    internetMonthly: 40000,
    childcareMonthly: 600000,
    localPurchasingPowerIndex: 74.3,
    groceriesIndex: 96.6,
    restaurantPriceIndex: 43.1,
  },
  {
    locationName: 'Prague',
    locationType: 'city',
    countryName: 'Czech Republic',
    currencyCode: 'CZK',
    averageMealCost: 250,
    monthlyRent1BR: 24000,
    monthlyRent2BR: 32000,
    monthlyRent3BR: 42000,
    transportPassCost: 550,
    utilitiesMonthly: 6500,
    internetMonthly: 700,
    childcareMonthly: 12000,
    localPurchasingPowerIndex: 71.2,
    groceriesIndex: 50.8,
    restaurantPriceIndex: 42.5,
  },
  {
    locationName: 'Amsterdam',
    locationType: 'city',
    countryName: 'Netherlands',
    currencyCode: 'EUR',
    averageMealCost: 20,
    monthlyRent1BR: 1850,
    monthlyRent2BR: 2400,
    monthlyRent3BR: 3100,
    transportPassCost: 100,
    utilitiesMonthly: 230,
    internetMonthly: 45,
    childcareMonthly: 1800,
    localPurchasingPowerIndex: 89.9,
    groceriesIndex: 65.4,
    restaurantPriceIndex: 84.1,
  },
];
