
import type { School, TeacherProfile } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return {
    imageUrl: image?.imageUrl ?? "https://picsum.photos/seed/placeholder/600/400",
    imageHint: image?.imageHint ?? "school building"
  };
};

export const teacherProfile: TeacherProfile = {
  id: "agent-001",
  fullName: "Jane Doe",
  avatarUrl: "https://images.unsplash.com/photo-1580894908361-967195033215?q=80&w=2070&auto=format&fit=crop",
  isVerifiedTeacher: true,
  familyStatus: "Couple",
  ageGroup: "35-49",
  memberSince: new Date("2022-08-15"),
  yearsOfExperience: 12,
  qualifications: ["PGCE", "Master's in Education", "NPQSL"],
  linkedInProfileUrl: "https://www.linkedin.com/in/example",
  preferredRegions: ["Southeast Asia", "Middle East"],
  preferredCountries: ["Thailand", "UAE", "Singapore"],
};

export const schools: School[] = [
  {
    id: 'tokyo-international-school',
    name: 'Tokyo International School',
    description: 'A forward-thinking IB school focused on nurturing inquisitive, lifelong learners in the heart of Tokyo, transitioning to a brand-new campus in 2026.',
    websiteUrl: 'https://www.tokyois.com',
    location: 'Tokyo',
    country: 'Japan',
    ...getImage('tokyo-international-school'),
    videoUrl: 'https://www.youtube.com/embed/GZ4d3HEn93c',
    spotlight: true,
    intel: {
      salary: { value: 'JPY 7M – 10M', score: 'good' },
      housing: { value: 'Allowance (JPY 150k-200k)', provided: false },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'IB',
      studentTeacherRatio: '9:1',
      classSize: 20,
      healthInsurance: 'Comp (PMAC)',
      accreditation: 'CIS, WASC',
      jobsPortal: 'TES, Search Associates',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Sponsored Instructor Visa',
      benefitsSummary: 'Comprehensive health, relocation allowance.',
      nonContactTime: 22,
      technologyEcosystem: '1:1 iPads, Google Workspace'
    },
    costOfLiving: { monthlyRent1BR: 160000, monthlyRent2BR: 250000, monthlyRent3BR: 400000, food: 70000, transport: 15000, utilities: 20000, internet: 5000, mobile: 4000, diningSocial: 30000, vehicleInsuranceMaint: 0, uncoveredMedical: 10000 },
  },
  {
    id: 'gems-dubai-american-academy',
    name: 'GEMS Dubai American Academy',
    description: 'The flagship American school in Dubai, blending the enriched US curriculum with the IB Diploma in a luxury facility. Consistently rated Outstanding.',
    websiteUrl: 'https://www.gemsaa-dubai.com/',
    location: 'Dubai',
    country: 'UAE',
    ...getImage('dubai-american-academy'),
    videoUrl: 'https://www.youtube.com/embed/U2f8_L-5L_w',
    spotlight: true,
    intel: {
      salary: { value: 'AED 144,000 – 210,000', score: 'good', isTaxFree: true },
      housing: { value: 'Provided or High Allowance', provided: true },
      savingsPotential: { value: 'V High', score: 'good' },
      curriculum: 'US, IB',
      studentTeacherRatio: '12:1',
      classSize: 24,
      healthInsurance: 'Elite (Global Private)',
      accreditation: 'NEASC',
      jobsPortal: 'GRC, School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'School Sponsors All Visas',
      benefitsSummary: 'Full medical, annual flights, PD fund.',
      nonContactTime: 20,
      technologyEcosystem: '1:1 MacBooks, iPads, PowerSchool'
    },
    costOfLiving: { monthlyRent1BR: 7500, monthlyRent2BR: 11000, monthlyRent3BR: 15000, food: 2200, transport: 500, utilities: 700, internet: 300, mobile: 200, diningSocial: 500, vehicleInsuranceMaint: 150, uncoveredMedical: 50 },
  },
  {
    id: 'zurich-international-school',
    name: 'Zurich International School',
    description: 'A leading non-profit school offering both the IB Diploma and AP courses in a stunning alpine setting. Known for extreme liveability.',
    websiteUrl: 'https://www.zis.ch/',
    location: 'Zurich',
    country: 'Switzerland',
    ...getImage('zurich-international-school'),
    videoUrl: 'https://www.youtube.com/embed/j1wB-G73b7A',
    spotlight: true,
    intel: {
      salary: { value: 'CHF 100,000 – 125,000', score: 'good' },
      housing: { value: 'Not Provided (Relocation assistance)', provided: false },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'IB, US',
      studentTeacherRatio: '7:1',
      classSize: 18,
      healthInsurance: 'Elite (Mandatory Private)',
      accreditation: 'CIS, NEASC',
      jobsPortal: 'School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Strict Quotas for non-EU',
      benefitsSummary: 'Generous pension, lunch vouchers.',
      nonContactTime: 20,
      technologyEcosystem: 'BYOD, Canvas, Veracross'
    },
    costOfLiving: { monthlyRent1BR: 2300, monthlyRent2BR: 3200, monthlyRent3BR: 4500, food: 900, transport: 200, utilities: 300, internet: 70, mobile: 60, diningSocial: 600, vehicleInsuranceMaint: 200, uncoveredMedical: 200 },
  },
  {
    id: 'singapore-american-school',
    name: 'Singapore American School',
    description: 'A global leader in American international education providing a personalized and innovative experience with unparalleled resources.',
    websiteUrl: 'https://www.sas.edu.sg/',
    location: 'Singapore',
    country: 'Singapore',
    ...getImage('singapore-american-school'),
    intel: {
      salary: { value: 'SGD 120,000 – 165,000', score: 'good' },
      housing: { value: 'Allowance (SGD 3,000+)', provided: false },
      savingsPotential: { value: 'V High', score: 'good' },
      curriculum: 'US',
      studentTeacherRatio: '11:1',
      classSize: 22,
      healthInsurance: 'Elite (Global Private)',
      accreditation: 'WASC',
      jobsPortal: 'ISS, School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'S-Pass or EP Sponsorship',
      benefitsSummary: 'Full medical, annual flights, relocation.',
      nonContactTime: 20,
      technologyEcosystem: '1:1 MacBooks, Google Workspace'
    },
    costOfLiving: { monthlyRent1BR: 3800, monthlyRent2BR: 5200, monthlyRent3BR: 7000, food: 900, transport: 150, utilities: 300, internet: 60, mobile: 50, diningSocial: 400, vehicleInsuranceMaint: 0, uncoveredMedical: 80 },
  },
  {
    id: 'seoul-foreign-school',
    name: 'Seoul Foreign School',
    description: 'A top-tier Christian-ethos school offering a diverse range of international curricula on a massive, resource-rich campus.',
    websiteUrl: 'https://www.seoulforeign.org/',
    location: 'Seoul',
    country: 'South Korea',
    ...getImage('seoul-foreign-school'),
    intel: {
      salary: { value: 'KRW 65M – 95M', score: 'good' },
      housing: { value: 'On-campus Provided', provided: true },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'IB, US, UK',
      studentTeacherRatio: '8:1',
      classSize: 20,
      healthInsurance: 'Comp (NHIS + Private)',
      accreditation: 'WASC, CIS',
      jobsPortal: 'TES, School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Sponsored E-2 or E-7',
      benefitsSummary: 'National health, severance pay, airfare.',
      nonContactTime: 20,
      technologyEcosystem: 'Google Workspace, 1:1 program'
    },
    costOfLiving: { monthlyRent1BR: 1400000, monthlyRent2BR: 2200000, monthlyRent3BR: 3500000, food: 750000, transport: 100000, utilities: 250000, internet: 40000, mobile: 30000, diningSocial: 250000, vehicleInsuranceMaint: 0, uncoveredMedical: 70000 },
  },
  {
    id: 'international-school-amsterdam',
    name: 'International School of Amsterdam',
    description: 'A collaborative learning community offering the full IB continuum in a high-tech, sustainable campus. Prestigious and sustainable.',
    websiteUrl: 'https://www.isa.nl/',
    location: 'Amsterdam',
    country: 'Netherlands',
    ...getImage('amsterdam-international-school'),
    intel: {
      salary: { value: '€52,000 – €82,000', score: 'good' },
      housing: { value: 'Allowance (€1,000-€1,500)', provided: false },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'IB (PYP, MYP, DP)',
      studentTeacherRatio: '11:1',
      classSize: 20,
      healthInsurance: 'Comp (Hybrid System)',
      accreditation: 'CIS, NEASC',
      jobsPortal: 'School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Strong preference for EU/EEA',
      benefitsSummary: '30% Tax Ruling eligibility, pension.',
      nonContactTime: 22,
      technologyEcosystem: 'Google Workspace, Sustainable campus'
    },
    costOfLiving: { monthlyRent1BR: 1850, monthlyRent2BR: 2400, monthlyRent3BR: 3100, food: 450, transport: 150, utilities: 200, internet: 55, mobile: 45, diningSocial: 350, vehicleInsuranceMaint: 0, uncoveredMedical: 120 },
  },
  {
    id: 'the-english-college-prague',
    name: 'The English College in Prague',
    description: 'A selective, non-profit HMC IB World School providing a transformative British-style education in a historic city.',
    websiteUrl: 'https://www.englishcollege.cz',
    location: 'Prague',
    country: 'Czech Republic',
    ...getImage('english-college-prague'),
    intel: {
      salary: { value: 'CZK 950,000 – 1,400,000', score: 'good' },
      housing: { value: 'Relocation assistance only', provided: false },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'UK, IB',
      studentTeacherRatio: '10:1',
      classSize: 18,
      healthInsurance: 'State (Excellent public system)',
      accreditation: 'HMC, IBO',
      jobsPortal: 'TES, School Website',
      minQualifications: 'Degree + PGCE/QTS',
      visaRestrictions: 'Sponsored Employee Card',
      benefitsSummary: 'Flight allowance, public health insurance.',
      nonContactTime: 25,
      technologyEcosystem: 'Google Workspace, BYOD'
    },
    costOfLiving: { monthlyRent1BR: 24000, monthlyRent2BR: 32000, monthlyRent3BR: 42000, food: 9500, transport: 2000, utilities: 5000, internet: 700, mobile: 600, diningSocial: 7500, vehicleInsuranceMaint: 0, uncoveredMedical: 1200 },
  }
];
