
import type { School, TeacherProfile } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return {
    imageUrl: image?.imageUrl ?? "https://picsum.photos/seed/placeholder/600/400",
    imageHint: image?.imageHint ?? "school building"
  };
};

export const teacherProfile: TeacherProfile = {
  id: "agent-001",
  fullName: "Jane Doe",
  avatarUrl: "https://images.unsplash.com/photo-1580894908361-967195033215?q=80&w=2070&auto=format&fit=crop",
  isVerifiedTeacher: true,
  familyStatus: "Couple",
  ageGroup: "35-49",
  memberSince: new Date("2022-08-15"),
  yearsOfExperience: 12,
  qualifications: ["PGCE", "Master's in Education", "NPQSL"],
  linkedInProfileUrl: "https://www.linkedin.com/in/example",
  preferredRegions: ["Southeast Asia", "Middle East"],
  preferredCountries: ["Thailand", "UAE", "Singapore"],
};

export const schools: School[] = [
  {
    id: 'tokyo-international-school',
    name: 'Tokyo International School',
    description: 'A forward-thinking IB school focused on nurturing inquisitive, lifelong learners in the heart of Tokyo, transitioning to a brand-new campus in 2026.',
    websiteUrl: 'https://www.tokyois.com',
    location: 'Tokyo',
    country: 'Japan',
    ...getImage('tokyo-international-school'),
    videoUrl: 'https://www.youtube.com/embed/GZ4d3HEn93c',
    spotlight: true,
    intel: {
      salary: { value: 'JPY 7M – 10M', score: 'good' },
      housing: { value: 'Monthly Allowance', provided: false },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'IB',
      studentTeacherRatio: '9:1',
      classSize: 20,
      healthInsurance: 'Comp (PMAC)',
      accreditation: 'CIS, WASC',
      jobsPortal: 'TES, Search Associates',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Sponsored Instructor Visa',
      benefitsSummary: 'Comprehensive health, relocation allowance.',
      nonContactTime: 22,
      technologyEcosystem: '1:1 iPads, Google Workspace'
    },
    costOfLiving: { monthlyRent1BR: 160000, monthlyRent2BR: 250000, monthlyRent3BR: 400000, food: 70000, transport: 15000, utilities: 20000, internet: 5000, mobile: 4000, diningSocial: 30000, vehicleInsuranceMaint: 0, uncoveredMedical: 10000 },
    stabilityMetrics: { crudeTurnoverRate: 12, fiveYearAnchorRate: 35, leadershipTenure: 6, stabilityScore: 86, stabilityRating: 'High', redFlagAlert: false }
  },
  {
    id: 'gems-dubai-american-academy',
    name: 'GEMS Dubai American Academy',
    description: 'The flagship American school in Dubai, blending the enriched US curriculum with the IB Diploma in a luxury facility. Consistently rated Outstanding.',
    websiteUrl: 'https://www.gemsaa-dubai.com/',
    location: 'Dubai',
    country: 'UAE',
    ...getImage('dubai-american-academy'),
    videoUrl: 'https://www.youtube.com/embed/U2f8_L-5L_w',
    spotlight: true,
    intel: {
      salary: { value: 'AED 144,000 – 210,000', score: 'good', isTaxFree: true },
      housing: { value: 'Furnished Apartment Provided', provided: true },
      savingsPotential: { value: 'V High', score: 'good' },
      curriculum: 'US, IB',
      studentTeacherRatio: '12:1',
      classSize: 24,
      healthInsurance: 'Elite (Global Private)',
      accreditation: 'NEASC',
      jobsPortal: 'GRC, School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'School Sponsors All Visas',
      benefitsSummary: 'Full medical, annual flights, PD fund.',
      nonContactTime: 20,
      technologyEcosystem: '1:1 MacBooks, iPads, PowerSchool'
    },
    costOfLiving: { monthlyRent1BR: 7500, monthlyRent2BR: 11000, monthlyRent3BR: 15000, food: 2200, transport: 500, utilities: 700, internet: 300, mobile: 200, diningSocial: 500, vehicleInsuranceMaint: 150, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 9, fiveYearAnchorRate: 42, leadershipTenure: 5, stabilityScore: 91, stabilityRating: 'Elite', redFlagAlert: false }
  },
  {
    id: 'repton-school-abu-dhabi',
    name: 'Repton School Abu Dhabi',
    description: 'A prestigious "Outstanding" rated school across two campuses, known for academic excellence and elite sports facilities on Al Reem Island.',
    websiteUrl: 'https://www.reptonabudhabi.org/',
    location: 'Abu Dhabi',
    country: 'UAE',
    ...getImage('repton-abu-dhabi'),
    intel: {
      salary: { value: 'AED 144,000 – 198,000', score: 'good', isTaxFree: true },
      housing: { value: 'Premium Apartment Provided', provided: true },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'UK National Curriculum',
      studentTeacherRatio: '10:1',
      classSize: 22,
      healthInsurance: 'Elite (Extensive Global)',
      accreditation: 'ADEK Outstanding',
      jobsPortal: 'School Website, TES',
      minQualifications: 'Degree + PGCE/License + 2 Yrs Exp',
      visaRestrictions: 'Standard UAE Residency',
      benefitsSummary: 'Elite health coverage, annual flights, gratuity scheme.',
      nonContactTime: 20,
      technologyEcosystem: 'Apple Distinguished School, 1:1 iPads'
    },
    costOfLiving: { monthlyRent1BR: 5500, monthlyRent2BR: 8500, monthlyRent3BR: 11500, food: 1500, transport: 400, utilities: 800, internet: 350, mobile: 200, diningSocial: 450, vehicleInsuranceMaint: 100, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 8, fiveYearAnchorRate: 45, leadershipTenure: 7, stabilityScore: 92, stabilityRating: 'Elite', redFlagAlert: false }
  },
  {
    id: 'british-international-school-abu-dhabi',
    name: 'The British International School Abu Dhabi',
    description: 'A Nord Anglia flagship school offering a globally recognized blend of British and IB pathways with an "Outstanding" rating in Zayed City.',
    websiteUrl: 'https://www.nordangliaeducation.com/bis-abu-dhabi',
    location: 'Abu Dhabi',
    country: 'UAE',
    ...getImage('bis-abu-dhabi'),
    intel: {
      salary: { value: 'AED 138,000 – 186,000', score: 'good', isTaxFree: true },
      housing: { value: 'Furnished Housing Provided', provided: true },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'UK, IB',
      studentTeacherRatio: '11:1',
      classSize: 20,
      healthInsurance: 'Elite (Comprehensive Private)',
      accreditation: 'ADEK Outstanding, CIS',
      jobsPortal: 'Nord Anglia Careers',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Sponsored by Nord Anglia',
      benefitsSummary: 'Nord Anglia University PD, annual flights.',
      nonContactTime: 18,
      technologyEcosystem: 'Global Campus integration, STEAM labs'
    },
    costOfLiving: { monthlyRent1BR: 4800, monthlyRent2BR: 7200, monthlyRent3BR: 9500, food: 1400, transport: 300, utilities: 800, internet: 350, mobile: 200, diningSocial: 450, vehicleInsuranceMaint: 100, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 14, fiveYearAnchorRate: 32, leadershipTenure: 4, stabilityScore: 85, stabilityRating: 'High', redFlagAlert: false }
  },
  {
    id: 'al-mamoura-academy',
    name: 'Al Mamoura Academy',
    description: 'A mixed-primary and girls-only secondary school in Abu Dhabi, part of the Aldar Education network, following the British curriculum.',
    websiteUrl: 'https://www.mamourabritishacademy.ae',
    location: 'Abu Dhabi',
    country: 'UAE',
    ...getImage('al-mamoura'),
    intel: {
      salary: { value: 'AED 126,000 – 168,000', score: 'neutral', isTaxFree: true },
      housing: { value: 'Monthly Allowance', provided: false },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'UK',
      studentTeacherRatio: '12:1',
      classSize: 24,
      healthInsurance: 'Comp',
      accreditation: 'ADEK Very Good',
      jobsPortal: 'Aldar Careers',
      minQualifications: 'Degree + License',
      visaRestrictions: 'UAE Ministry Approval Required',
      benefitsSummary: 'Health, flights, Aldar network benefits.',
      nonContactTime: 15,
      technologyEcosystem: 'Microsoft Showcase School'
    },
    costOfLiving: { monthlyRent1BR: 5000, monthlyRent2BR: 7500, monthlyRent3BR: 10000, food: 1400, transport: 1300, utilities: 800, internet: 350, mobile: 200, diningSocial: 450, vehicleInsuranceMaint: 100, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 18, fiveYearAnchorRate: 25, leadershipTenure: 3, stabilityScore: 72, stabilityRating: 'Medium', redFlagAlert: false }
  },
  {
    id: 'al-yasmina-academy',
    name: 'Al Yasmina Academy',
    description: 'An Outstanding Aldar Academy that has recently transitioned to a massive new state-of-the-art campus in Khalifa City.',
    websiteUrl: 'https://www.alyasminaacademy.ae',
    location: 'Abu Dhabi',
    country: 'UAE',
    ...getImage('al-yasmina'),
    intel: {
      salary: { value: 'AED 132,000 – 180,000', score: 'good', isTaxFree: true },
      housing: { value: 'Provided or Allowance', provided: true },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'UK',
      studentTeacherRatio: '10:1',
      classSize: 22,
      healthInsurance: 'Elite',
      accreditation: 'ADEK Outstanding',
      jobsPortal: 'Aldar Careers',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Standard Aldar Sponsorship',
      benefitsSummary: 'Premium health (incl. dental), flights.',
      nonContactTime: 17,
      technologyEcosystem: 'Advanced campus-wide tech'
    },
    costOfLiving: { monthlyRent1BR: 4500, monthlyRent2BR: 6800, monthlyRent3BR: 9000, food: 1300, transport: 1100, utilities: 800, internet: 350, mobile: 200, diningSocial: 450, vehicleInsuranceMaint: 100, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 11, fiveYearAnchorRate: 38, leadershipTenure: 5, stabilityScore: 88, stabilityRating: 'High', redFlagAlert: false }
  },
  {
    id: 'amity-international-school-abu-dhabi',
    name: 'Amity International School Abu Dhabi',
    description: 'A vibrant school with a unique focus on sailing and water sports, following the British National Curriculum in Al Bahya.',
    websiteUrl: 'https://www.amityabudhabi.com/',
    location: 'Abu Dhabi',
    country: 'UAE',
    ...getImage('amity-abu-dhabi'),
    intel: {
      salary: { value: 'AED 120,000 – 156,000', score: 'neutral', isTaxFree: true },
      housing: { value: 'Accommodation or Allowance', provided: true },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'UK',
      studentTeacherRatio: '13:1',
      classSize: 25,
      healthInsurance: 'Comp',
      accreditation: 'ADEK Very Good',
      jobsPortal: 'School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Standard processing',
      benefitsSummary: 'Health, flights, maritime facilities access.',
      nonContactTime: 15,
      technologyEcosystem: 'STEAM integration focus'
    },
    costOfLiving: { monthlyRent1BR: 4000, monthlyRent2BR: 6000, monthlyRent3BR: 8500, food: 1200, transport: 1000, utilities: 800, internet: 350, mobile: 200, diningSocial: 450, vehicleInsuranceMaint: 100, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 22, fiveYearAnchorRate: 20, leadershipTenure: 2, stabilityScore: 68, stabilityRating: 'Medium', redFlagAlert: false }
  },
  {
    id: 'diyafah-international-school',
    name: 'Diyafah International School',
    description: 'Providing an affordable British education to a diverse community in MBZ City, focused on academic and personal development.',
    websiteUrl: 'https://www.diyafahinternationalschool.com',
    location: 'Abu Dhabi',
    country: 'UAE',
    ...getImage('diyafah'),
    intel: {
      salary: { value: 'AED 102,000 – 138,000', score: 'neutral', isTaxFree: true },
      housing: { value: 'Basic Housing Provided', provided: true },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'UK',
      studentTeacherRatio: '15:1',
      classSize: 28,
      healthInsurance: 'Comp',
      accreditation: 'ADEK Good',
      jobsPortal: 'School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'UAE MoE Teaching License Required',
      benefitsSummary: 'Standard UAE healthcare, annual flights.',
      nonContactTime: 12,
      technologyEcosystem: 'General ICT labs'
    },
    costOfLiving: { monthlyRent1BR: 3500, monthlyRent2BR: 5500, monthlyRent3BR: 7500, food: 1100, transport: 900, utilities: 800, internet: 350, mobile: 200, diningSocial: 450, vehicleInsuranceMaint: 100, uncoveredMedical: 50 },
    stabilityMetrics: { crudeTurnoverRate: 28, fiveYearAnchorRate: 15, leadershipTenure: 2, stabilityScore: 55, stabilityRating: 'Low', redFlagAlert: true, redFlagReasoning: 'High churn detected in budget sector recruitment cycles.' }
  },
  {
    id: 'the-english-college-prague',
    name: 'The English College in Prague',
    description: 'A selective, non-profit HMC IB World School. It offers a prestigious British-style grammar school education for students aged 13–19.',
    websiteUrl: 'https://www.englishcollege.cz',
    location: 'Prague',
    country: 'Czech Republic',
    ...getImage('english-college-prague'),
    intel: {
      salary: { value: 'CZK 750k – 1.14M', score: 'good' },
      housing: { value: 'Not Provided (Relocation support)', provided: false },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'IB, IGCSE',
      studentTeacherRatio: '9:1',
      classSize: 18,
      healthInsurance: 'State (Czech Public)',
      accreditation: 'HMC, IBO',
      jobsPortal: 'TES, School Website',
      minQualifications: 'Degree + PGCE/QTS',
      visaRestrictions: 'Requires Sponsored Employee Card',
      benefitsSummary: 'Flight allowance, public health insurance.',
      nonContactTime: 25,
      technologyEcosystem: 'Google Workspace, BYOD'
    },
    costOfLiving: { monthlyRent1BR: 24000, monthlyRent2BR: 32000, monthlyRent3BR: 42000, food: 9500, transport: 2000, utilities: 5000, internet: 700, mobile: 600, diningSocial: 7500, vehicleInsuranceMaint: 0, uncoveredMedical: 1200 },
    stabilityMetrics: { crudeTurnoverRate: 15, fiveYearAnchorRate: 30, leadershipTenure: 4, stabilityScore: 82, stabilityRating: 'High', redFlagAlert: false }
  },
  {
    id: 'zurich-international-school',
    name: 'Zurich International School',
    description: 'A leading non-profit school offering both the IB Diploma and AP courses in a stunning alpine setting. Known for extreme liveability.',
    websiteUrl: 'https://www.zis.ch/',
    location: 'Zurich',
    country: 'Switzerland',
    ...getImage('zurich-international-school'),
    videoUrl: 'https://www.youtube.com/embed/j1wB-G73b7A',
    spotlight: true,
    intel: {
      salary: { value: 'CHF 100,000 – 125,000', score: 'good' },
      housing: { value: 'Not Provided (Relocation assistance)', provided: false },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'IB, US',
      studentTeacherRatio: '7:1',
      classSize: 18,
      healthInsurance: 'Elite (Mandatory Private)',
      accreditation: 'CIS, NEASC',
      jobsPortal: 'School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Strict Quotas for non-EU',
      benefitsSummary: 'Generous pension, lunch vouchers.',
      nonContactTime: 20,
      technologyEcosystem: 'Bring Your Own Device (BYOD), Canvas, Veracross'
    },
    costOfLiving: { monthlyRent1BR: 2300, monthlyRent2BR: 3200, monthlyRent3BR: 4500, food: 900, transport: 200, utilities: 300, internet: 70, mobile: 60, diningSocial: 600, vehicleInsuranceMaint: 200, uncoveredMedical: 200 },
    stabilityMetrics: { crudeTurnoverRate: 6, fiveYearAnchorRate: 50, leadershipTenure: 8, stabilityScore: 95, stabilityRating: 'Elite', redFlagAlert: false }
  },
  {
    id: 'singapore-american-school',
    name: 'Singapore American School',
    description: 'A global leader in American international education with unparalleled resources. Providing a personalized and innovative American educational experience.',
    websiteUrl: 'https://www.sas.edu.sg/',
    location: 'Singapore',
    country: 'Singapore',
    ...getImage('singapore-american-school'),
    intel: {
      salary: { value: 'SGD 120,000 – 165,000', score: 'good' },
      housing: { value: 'Monthly Allowance (SGD 3,000+)', provided: false },
      savingsPotential: { value: 'V High', score: 'good' },
      curriculum: 'US',
      studentTeacherRatio: '11:1',
      classSize: 22,
      healthInsurance: 'Elite (Global Private)',
      accreditation: 'WASC',
      jobsPortal: 'ISS, School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'S-Pass or EP sponsorship',
      benefitsSummary: 'Full medical, annual flights, relocation.',
      nonContactTime: 20,
      technologyEcosystem: '1:1 MacBooks, Google Workspace'
    },
    costOfLiving: { monthlyRent1BR: 3800, monthlyRent2BR: 5200, monthlyRent3BR: 7000, food: 900, transport: 150, utilities: 300, internet: 60, mobile: 50, diningSocial: 400, vehicleInsuranceMaint: 0, uncoveredMedical: 80 },
    stabilityMetrics: { crudeTurnoverRate: 5, fiveYearAnchorRate: 55, leadershipTenure: 10, stabilityScore: 98, stabilityRating: 'Elite', redFlagAlert: false }
  },
  {
    id: 'seoul-foreign-school',
    name: 'Seoul Foreign School',
    description: 'A top-tier Christian-ethos school offering a diverse range of international curricula on a massive campus.',
    websiteUrl: 'https://www.seoulforeign.org/',
    location: 'Seoul',
    country: 'South Korea',
    ...getImage('seoul-foreign-school'),
    intel: {
      salary: { value: 'KRW 65M – 95M', score: 'good' },
      housing: { value: 'On-campus Provided', provided: true },
      savingsPotential: { value: 'High', score: 'good' },
      curriculum: 'IB, US, UK',
      studentTeacherRatio: '8:1',
      classSize: 20,
      healthInsurance: 'Comp (NHIS + Private)',
      accreditation: 'WASC, CIS',
      jobsPortal: 'TES, School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Sponsored E-2 or E-7',
      benefitsSummary: 'National health, severance pay, airfare.',
      nonContactTime: 20,
      technologyEcosystem: 'Google Workspace, 1:1 program'
    },
    costOfLiving: { monthlyRent1BR: 1400000, monthlyRent2BR: 2200000, monthlyRent3BR: 3500000, food: 750000, transport: 100000, utilities: 250000, internet: 40000, mobile: 30000, diningSocial: 250000, vehicleInsuranceMaint: 0, uncoveredMedical: 70000 },
    stabilityMetrics: { crudeTurnoverRate: 7, fiveYearAnchorRate: 48, leadershipTenure: 6, stabilityScore: 94, stabilityRating: 'Elite', redFlagAlert: false }
  },
  {
    id: 'international-school-amsterdam',
    name: 'International School of Amsterdam',
    description: 'A collaborative learning community offering the full IB continuum in a high-tech, sustainable campus. Prestigious and sustainable.',
    websiteUrl: 'https://www.isa.nl/',
    location: 'Amsterdam',
    country: 'Netherlands',
    ...getImage('amsterdam-international-school'),
    intel: {
      salary: { value: '€52,000 – €82,000', score: 'good' },
      housing: { value: 'Monthly Allowance (€1,000-€1,500)', provided: false },
      savingsPotential: { value: 'Moderate', score: 'neutral' },
      curriculum: 'IB (PYP, MYP, DP)',
      studentTeacherRatio: '11:1',
      classSize: 20,
      healthInsurance: 'Comp (Hybrid System)',
      accreditation: 'CIS, NEASC',
      jobsPortal: 'School Website',
      minQualifications: 'Degree + License',
      visaRestrictions: 'Strong preference for EU/EEA',
      benefitsSummary: '30% Tax Ruling eligibility, pension.',
      nonContactTime: 22,
      technologyEcosystem: 'Google Workspace, Sustainable campus'
    },
    costOfLiving: { monthlyRent1BR: 1850, monthlyRent2BR: 2400, monthlyRent3BR: 3100, food: 450, transport: 150, utilities: 200, internet: 55, mobile: 45, diningSocial: 350, vehicleInsuranceMaint: 0, uncoveredMedical: 120 },
    stabilityMetrics: { crudeTurnoverRate: 12, fiveYearAnchorRate: 35, leadershipTenure: 5, stabilityScore: 80, stabilityRating: 'High', redFlagAlert: false }
  }
];
